# Generated by Django 4.0.6 on 2022-08-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicebench', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
