# Generated by Django 4.0.6 on 2022-08-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicebench', '0002_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pw_changed',
            field=models.BooleanField(default=False),
        ),
    ]
