# Generated by Django 4.0.6 on 2022-08-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicebench', '0003_user_pw_changed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.TextField()),
                ('tel', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=64)),
            ],
        ),
    ]
