# Generated by Django 4.0.6 on 2022-08-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicebench', '0004_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
