# Generated by Django 4.0.6 on 2022-09-02 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicebench', '0005_alter_customer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=64)),
                ('problem', models.TextField()),
                ('type', models.CharField(choices=[('f', 'Field'), ('w', 'Workshop'), ('r', 'Remote')], max_length=1)),
                ('status', models.CharField(choices=[('n', 'New'), ('s', 'Started'), ('h', 'Hold'), ('r', 'Resolved')], max_length=1)),
                ('log_time', models.DateField()),
                ('accept_time', models.DateField()),
                ('hold_reason', models.TextField()),
                ('resolved_time', models.DateField()),
                ('resolution', models.TextField()),
                ('accept_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='servicebench.customer')),
            ],
        ),
    ]
