# Generated by Django 4.0.6 on 2022-09-04 19:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicebench', '0006_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='accept_time',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='accept_user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='hold_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='log_time',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='resolution',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='resolved_time',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('n', 'New'), ('s', 'Started'), ('h', 'Hold'), ('r', 'Resolved')], max_length=1),
        ),
    ]
