# Generated by Django 4.0.6 on 2022-09-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicebench', '0007_alter_task_accept_time_alter_task_accept_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='accept_time',
            field=models.DateField(null=True),
        ),
    ]
