# Generated by Django 4.0.6 on 2022-09-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicebench', '0008_alter_task_accept_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='resolved_time',
            field=models.DateField(null=True),
        ),
    ]
