# Generated by Django 4.0.6 on 2022-09-04 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicebench', '0009_alter_task_resolved_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='accept_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
