# Generated by Django 4.0.6 on 2022-09-04 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicebench', '0010_alter_task_accept_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='accept_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='log_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='resolved_time',
            field=models.DateTimeField(null=True),
        ),
    ]
