# Generated by Django 4.0.6 on 2022-09-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicebench', '0011_alter_task_accept_time_alter_task_log_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('n', 'New'), ('s', 'Started'), ('h', 'Hold'), ('r', 'Resolved')], default='n', max_length=1),
        ),
    ]
