# Generated by Django 4.0.6 on 2022-09-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicebench', '0013_task_invoiced'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='labour_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='travel_distance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='travel_time',
            field=models.IntegerField(default=0),
        ),
    ]
